<a href="https://colab.research.google.com/github/zachtahajian5/end-to-end-RidgeCV/blob/main/IDmatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import

A = np.array(
    [[191_100_100, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]]
     )
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
ID = np.eye(3)
print(ID)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# prompt: create random generator object

import numpy as np
rng = np.random.default_rng(42)



In [ ]:
# prompt: create a 3x2 array and a 9x3 array with random elements using the generator object

array_3x2 = rng.random((3, 2))
print(array_3x2)

array_9x3 = rng.random((9, 3))




[[0.77395605 0.43887844]
 [0.85859792 0.69736803]
 [0.09417735 0.97562235]]


In [ ]:
print(array_9x3)

[[0.7611397  0.78606431 0.12811363]
 [0.45038594 0.37079802 0.92676499]
 [0.64386512 0.82276161 0.4434142 ]
 [0.22723872 0.55458479 0.06381726]
 [0.82763117 0.6316644  0.75808774]
 [0.35452597 0.97069802 0.89312112]
 [0.7783835  0.19463871 0.466721  ]
 [0.04380377 0.15428949 0.68304895]
 [0.74476216 0.96750973 0.32582536]]


In [ ]:
c = array_9x3 @ array_3x2
print(c)

[[1.27606726 1.00721444]
 [0.7542256  1.36042   ]
 [1.24650429 1.28895097]
 [0.65804827 0.54874142]
 [1.25429058 1.54333938]
 [1.1919386  1.7038765 ]
 [0.81350555 0.93269399]
 [0.23070257 0.79321891]
 [1.43780039 1.31945291]]


In [ ]:
# prompt: id matrix 4x4 and rng array with shape 4,2

import numpy as np
ID4x4 = np.eye(4)
print(ID4x4)

rng_array_4x2 = rng.random((4, 2))
rng_array_4x2

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


array([[0.37045971, 0.46955581],
       [0.18947136, 0.12992151],
       [0.47570493, 0.22690935],
       [0.66981399, 0.43715192]])

In [ ]:
c_1 = ID4x4 @ rng_array_4x2



print(c_1)


[[0.37045971 0.46955581]
 [0.18947136 0.12992151]
 [0.47570493 0.22690935]
 [0.66981399 0.43715192]]


In [ ]:
# prompt: array with shape 4,2

rng_array_4x2 = rng.random((4, 2))
rng_array_4x2

array([[0.8326782 , 0.7002651 ],
       [0.31236664, 0.8322598 ],
       [0.80476436, 0.38747838],
       [0.2883281 , 0.6824955 ]])